# Generated by Django 3.0.7 on 2021-12-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogIn',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('isLoggedIn', models.CharField(max_length=30)),
            ],
        ),
    ]
