# Generated by Django 3.0.7 on 2021-12-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='isLoggedIn',
            field=models.CharField(default='True', max_length=30),
        ),
    ]
