# Generated by Django 3.0.7 on 2021-12-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_auto_20211206_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='isLoggedIn',
            field=models.BooleanField(default='True'),
        ),
    ]
