# Generated by Django 3.0.7 on 2021-12-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_auto_20211206_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='login_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
