# Generated by Django 3.0.7 on 2021-12-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_login_login_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='isLoggedIn',
            field=models.BooleanField(default=False),
        ),
    ]
