# Generated by Django 3.0.7 on 2021-10-31 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopInfo',
            fields=[
                ('shop_id', models.AutoField(primary_key=True, serialize=False)),
                ('shop_name', models.CharField(blank=True, max_length=50, null=True)),
                ('shop_contact', models.CharField(blank=True, max_length=10, null=True)),
                ('shop_email', models.CharField(blank=True, max_length=50, null=True)),
                ('shop_address', models.CharField(blank=True, max_length=50, null=True)),
                ('shop_type', models.CharField(blank=True, max_length=50, null=True)),
                ('shop_description', models.TextField(max_length=500)),
                ('shop_image', models.FileField(blank=True, null=True, upload_to='images/')),
                ('owner_name', models.CharField(blank=True, max_length=50, null=True)),
                ('owner_contact', models.CharField(blank=True, max_length=10, null=True)),
                ('owner_email', models.CharField(blank=True, max_length=50, null=True)),
                ('owner_address', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
