# Generated by Django 3.0.7 on 2021-11-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopinfo',
            name='shop_image',
            field=models.FileField(blank=True, default='media/images/logo.png', null=True, upload_to='images/'),
        ),
    ]
