# Generated by Django 3.0.7 on 2021-11-27 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_contactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopinfo',
            name='owner_address',
        ),
        migrations.RemoveField(
            model_name='shopinfo',
            name='owner_contact',
        ),
        migrations.RemoveField(
            model_name='shopinfo',
            name='owner_email',
        ),
        migrations.RemoveField(
            model_name='shopinfo',
            name='owner_name',
        ),
        migrations.CreateModel(
            name='OwnerInfo',
            fields=[
                ('owner_id', models.AutoField(primary_key=True, serialize=False)),
                ('owner_name', models.CharField(blank=True, max_length=50, null=True)),
                ('owner_contact', models.CharField(blank=True, max_length=10, null=True)),
                ('owner_email', models.CharField(blank=True, max_length=50, null=True)),
                ('owner_address', models.CharField(blank=True, max_length=50, null=True)),
                ('owner_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.ShopInfo')),
            ],
        ),
    ]
