# Generated by Django 3.0.7 on 2021-12-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20211127_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerinfo',
            name='owner_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='shop_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
